.TH dq 1
.SH NAME
dq \- DNS/DNSCurve query tool
.SH SYNOPSIS
.B dq
[ options ]
.I type
.I fqdn
[
.I host
]
.TP
.B dq -a
[ options ]
.I type
.I fqdn
.I host
.SH DESCRIPTION
.B dq
is commandline tool derived from
.B dnsq
/
.B dnsqr
(https://cr.yp.to/djbdns/debugging.html)
.sp
.B dq
asks for records of type
.I type
under the domain name
.I fqdn
.TP
.B dq -a
sends a non-recursive DNS/DNSCurve query to DNS/DNSCurve server
.I host
for records of type 
.I type
under the domain name 
.I fqdn
.SH OPTIONS
.TP
.B \-v
print extra information
.TP
.B \-r
send recursive query (default)
.TP
.B \-a
send authoritative query
.TP
.B \-u
use UDP (default)
.TP
.B \-t
use TCP
.TP
.B \-s
send DNSCurve query in streamlined format (default), ignored for regular DNS queries
.TP
.B \-S \fIsuffix
send DNSCurve query in TXT format using suffix
.IR suffix ,
ignored for regular DNS queries
.TP
.B \-T \fItimeout
give up on the DNS/DNSCurve query attempt after
.I timeout
seconds <1-60>
(default 60)
.TP
.B \-p \fIport
send query to port
.I port
(default 53)
.TP
.B \-k \fIkey
send DNSCurve query and use servers public-key
.I key
.TP
.I type
DNS query type (A, NS, MX, ANY, PTR, TXT, SOA, SRV, AAAA, AXFR, CNAME or numeric type)
.TP
.I fqdn
fully qualified domain name
.TP
.I host
DNS server (hostname or IP address)
.SH ENVIRONMENT
.TP
.B DNSCACHEIP
use IP address $DNSCACHEIP instead of 'nameserver' lines from /etc/resolv.conf
.TP
.B LOCALDOMAIN
use space separated names from $LOCALDOMAIN instead of 'search' line from /etc/resolv.conf
.TP
.B DNSREWRITEFILE
use $DNSREWRITEFILE file instead of /etc/dnsrewrite
.SH NOTES
.B dq
rewrites IP address to *.in-addr.arpa or *.ip6.arpa for PTR queries e.g.:
.nf
.RS 2
127.0.0.1 -> 1.0.0.127.in-addr.arpa
::1 -> 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
.RE
.SH RECURSIVE EXAMPLES
.nf
dq any dnscurve.cz
dq any dnscurve.cz 8.8.8.8
env DNSCACHEIP=8.8.8.8 dq any dnscurve.cz
dq ptr 1.0.0.127.in-addr.arpa
dq ptr 127.0.0.1
dq ptr ::1
dq ptr 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
.fi
.SH AUTHORITATIVE EXAMPLES
.nf
dq \-a any dnscurve.cz uz5mj60yr9tnudkkpcglw1y0w6dlh78j1l4gk4z7t8bsf1u4d48wlq.ns.dnscurve.cz
dq \-a \-S cz any dnscurve.cz uz5mj60yr9tnudkkpcglw1y0w6dlh78j1l4gk4z7t8bsf1u4d48wlq.ns.dnscurve.cz
dq \-a \-k uz5mj60yr9tnudkkpcglw1y0w6dlh78j1l4gk4z7t8bsf1u4d48wlq any dnscurve.cz 2a02:2b88:2:1::127d:1
.fi
.SH SEE ALSO
.BR dnsq (1),
.BR dnsqr (1),
.BR dqcache (8)
.sp
.nf
https://mojzis.com/software/dq
https://dnscurve.org/
https://cr.yp.to/djbdns/debugging.html
.fi
