.TH dqcache-makekey 1
.SH NAME
dqcache-makekey \- make DNSCurve secret-key for dqcache
.SH SYNOPSIS
.B dqcache-makekey
.SH DESCRIPTION
.B dqcache-makekey
creates secret-key (in hex format) for dqcache
.SH EXAMPLE
.nf
(
  cd /etc/dqcache/env/
  umask 077
  dqcache-makekey > SECRETKEY.tmp
  mv \-f SECRETKEY.tmp SECRETKEY
)
.fi
.SH SEE ALSO
.BR dqcache (8)
.sp
.nf
https://mojzis.com/software/dq
https://dnscurve.org/
.fi
