#!/bin/sh
exec 2>&1

ROOT=/etc/dqcache/root
export ROOT

DATALIMIT=`expr "${CACHESIZE}" + "${CACHESIZE}" + 1000000`
export DATALIMIT

exec envuidgid dqcache envdir /etc/dqcache/env sh -c '
    exec softlimit -o250 -d "${DATALIMIT}" /usr/bin/dqcache
'
