#!/bin/sh
exec 2>&1

exec envuidgid dqcache envdir /etc/dqcache/env sh -c '
    DATALIMIT=`expr "${CACHESIZE}" + "${CACHESIZE}" + 1000000`
    exec softlimit -o250 -d "${DATALIMIT}" /usr/sbin/dqcache
'
