#!/bin/sh -e

#crypto_uint*/crypto_int*
echo 'crypto_int8.h crypto_int8.h-char'
echo 'crypto_uint8.h crypto_uint8.h-char'

echo 'crypto_int16.h crypto_int16.h-short'
echo 'crypto_uint16.h crypto_uint16.h-short'

echo 'crypto_int32.h crypto_int32.h-int'
echo 'crypto_int32.h crypto_int32.h-long'
echo 'crypto_uint32.h crypto_uint32.h-int'
echo 'crypto_uint32.h crypto_uint32.h-long'

echo 'crypto_int64.h crypto_int64.h-longlong'
echo 'crypto_int64.h crypto_int64.h-long'
echo 'crypto_int64.h crypto_int64.h-attr'
echo 'crypto_uint64.h crypto_uint64.h-longlong'
echo 'crypto_uint64.h crypto_uint64.h-long'
echo 'crypto_uint64.h crypto_uint64.h-attr'

#hasipv6
echo 'hasipv6.h hasipv6.h-yes'
echo 'hasipv6.h default.h-no'

echo 'direntry.h direntry.h-dirent'
echo 'direntry.h direntry.h-direct'

#order
echo 'order.h order.h-little'
echo 'order.h order.h-big'
echo 'order.h default.h-no'

#__asm__ __volatile__ ...
echo 'hasasmvolatilememory.h hasasmvolatilememory.h-yes'
echo 'hasasmvolatilememory.h default.h-no'
